### PR TITLE
Add update instruction within `head`

### PR DESCRIPTION
**Pull request by pickfire**
The URL seems too long such that it is more than 80 columns.

### CODE REVIEW

**Comment by rpdelaney** [comment]
Hm not 100% sure that we want to pack the readme into the LS_COLORS file itself. But if we do, can you give the complete instructions from the readme? By itself that command won't do anything.

```sh
wget https://raw.github.com/trapd00r/LS_COLORS/master/LS_COLORS -O $HOME/.dircolors
echo 'eval $(dircolors -b $HOME/.dircolors)' >> $HOME/.bashrc
. $HOME/.bashrc
```

**Comment by pickfire** [comment]
Any news on this?

**Comment by rpdelaney** [comment]
Thanks for following up. I think #122 is blocking this PR.

**Comment by rpdelaney** [comment]
@pickfire What do you think about the comments I left in #122?

**Comment by rpdelaney** [comment]
I think we should deprecate the `echo 'eval $(dircolors -b $HOME/.dircolors)' >> $HOME/.bashrc` installation pattern in favor of the pre-computed approach used in the archlinux AUR and planned in #136.

Since the URl to the repository is in the header, if one comes across the `LS_COLORS` file in the wild they should be able to navigate back to our documentation.

**Pull request closed without merging**
