### PR TITLE
fix: Makefile syntax and whitespace quoting

### LINKED ISSUE #201: Invalid syntax in Makefile?
Looking at the `Makefile` again, [this](https://github.com/trapd00r/LS_COLORS/blame/7d06cdb4a245640c3665fe312eb206ae758092be/Makefile#L2) looks like it's invalid shell code:

```bash
export XDG_DATA_HOME ?= $${$$HOME/.local/share}
```

Based on my understanding, I would expect:

```bash
export XDG_DATA_HOME ?= $(HOME)/.local/share
```

However, I'm not a GNU Make guru. Is there some make magic going on here?

### PR DESCRIPTION
**Pull request by hyperupcall**
As mentioned in the linked issue, the previous syntax caused a syntax error if `XDG_DATA_HOME` was undefined.

```console
$ unset XDG_DATA_HOME
$ make install
/bin/sh: ${$HOME/.local/share}: bad substitution
make: *** [install] Error 1
```

This does away with the `$$` escaping, and leans into Make's standard `$()` substitution syntax. The logic goes like this:
- If `XDG_DATA_HOME` is not defined, assign it to `$HOME/.local/share` (now, value of `$HOME` is evaluated right away instead of being deferred; effectively changes nothing)
- Quote `$(XDG_DATA_HOME)`, in case parts of it contain whitespace (Make does not evaluate the quotation marks, Bash will once `$(XDG_DATA_HOME)` is substituted)

This also removes the `export` - it's not necessary

Closes #201

### CODE REVIEW

**Comment by rpdelaney** [comment]
Thanks so much for these PRs~! <3

I have such deep experience with GNU bash and so little experience with GNU make that when I look at this stuff my brain tells me Make is Bash with sugar, but it's not. I need to spend a little time going over the GNU make manual to grok this better.

One problem I'm chewing on is how we can add regression tests in CI for these things while we're at it. If you have any thoughts on that please let me know!

**Comment by hyperupcall** [comment]
> I have such deep experience with GNU bash and so little experience with GNU make that when I look at this stuff my brain tells me Make is Bash with sugar, but it's not. I need to spend a little time going over the GNU make manual to grok this better.

Haha I know the feeling - I still have to manually test my changes for Makefiles since it can be seemingly unpredictable sometimes.

> One problem I'm chewing on is how we can add regression tests in CI for these things while we're at it. If you have any thoughts on that please let me know!

Maybe I can add a `.github/workflows/ci.yaml` action that runs on `[pull_request]` and commits to `master`, running scripts in `~/tests`. And add a script for checking that the `XDG_` variable doesn't need to be defined for the script to succeed. I can do that in a separate PR

**Comment by rpdelaney** [comment]
> I can do that in a separate PR

That would be great since it would demonstrate that the test fails when it should. Test driven design! :) My plate is full today but I should be able to take a swing at it later this week; no hard feelings if you beat me to it.

**Comment by rpdelaney** [comment]
@hyperupcall Can you merge from `master`? It looks like collaborator edits wasn't checked

**Comment by hyperupcall** [comment]
Done! Unfortunately, GitHub does not seem to show show a collaborator edits checkbox when a fork is not from a personal account.

It looks like the tests pass :)

**Comment by rpdelaney** [comment]
Thank you! 💯

**Pull request merged**
