### PR TITLE
Commit generated files to the repo & automate the process through actions when PRs are merged.

### PR DESCRIPTION
**Pull request by ahmedelgabri**
@rpdelaney This should resolve these comments https://github.com/trapd00r/LS_COLORS/pull/136#issuecomment-1008016088 & https://github.com/trapd00r/LS_COLORS/pull/136#issuecomment-1017747753.

### CODE REVIEW

**Comment by rpdelaney** [comment]
Thank you very much for this!!

When I do `make` with no arguments, the files are deleted out of the repo. I think most users would expect to see the files rebuilt. Perhaps `generate` can simply be renamed to `all`?

cc @trapd00r : I just want to give you a heads up since this is a significant departure from how we've been distributing LS_COLORS in the past. But I do think it's a big improvement over the status quo.

**Comment by ahmedelgabri** [comment]
@rpdelaney update the PR & now `generate` is the default target.

**Comment by rpdelaney** [comment]
Awesome. Thanks again!

**Comment by paulirish** [comment]
Long-time user.. Dumb question... I never understood how the older source interacted with the `dircolors` command.. But can someone explain why `dircolors` isn't needed any longer? (Right now I'm seeing #158 and trying to figure out if things are broken…)

**Comment by paulirish** [comment]
> But can someone explain why `dircolors` isn't needed any longer? 

Derp. Okay I see that it's just done in the makefile and the post-dircolors file is now in the repo. 👍

**Pull request merged**
