### PR TITLE
buildsuite: create more special files

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by rpdelaney** [comment]
I'm disinclined to be hard-coding filenames except for specific purposes. Currently we do this to test the representation of files with various attributes. There's already a loop to generate files from the file `LS_COLORS`, so why don't we just add these there?

**Comment by blueyed** [comment]
Which loop?
There is one for extensions only.
We could have the same for filenames, but then duplicates (with the same attributes) should be skipped probably.

**Comment by rpdelaney** [comment]
Starts on line 118.

**Comment by blueyed** [comment]
Ah, missed the part where it created the files (https://github.com/trapd00r/LS_COLORS/pull/48/files#diff-bcff1978c9626f0cdd3b6949935d365dL125).

**Comment by blueyed** [comment]
What do you think about naming them e.g. `README` instead of `test.README`?
And then move them one dir up (into the root)?

**Comment by rpdelaney** [comment]
It will `touch test.extension` if and only if the file type starts with a dot `.`. Otherwise, it will simply `touch extension`. Therefore "README" should get generated correctly.

I admit that I could have done a better job commenting this script.

**Comment by blueyed** [comment]
It will replace the `*` with e.g. `README` with a `.`:

    line="${line//\*/.}"
    if [[ "${line:0:1}" == "." ]]; then

Therefore it creates `test.README`.

**Comment by rpdelaney** [comment]
You're right. I'll see if I can improve that.

**Pull request closed without merging**
