### PR TITLE
Fix GitHub action logic

### PR DESCRIPTION
**Pull request by ahmedelgabri**
Should fix https://github.com/trapd00r/LS_COLORS/pull/183#issuecomment-1019529504

### CODE REVIEW

**Comment by rpdelaney** [comment]
Thanks, let's see :)

**Comment by rpdelaney** [comment]
Looks like a build fail :( https://github.com/trapd00r/LS_COLORS/actions/runs/1737140676

**Comment by rpdelaney** [comment]
@trapd00r I'm not able to access the repo settings. Can you help?

**Comment by ahmedelgabri** [comment]
Might be that it needs this, but I also have a similar workflow working without the token so I'm a bit confused. 

It's already set by GitHub automatically https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow

Could you try adding this to this section https://github.com/ahmedelgabri/LS_COLORS/blob/72504cb599e0e61d0c4e47245e38ee886a265f8c/.github/workflows/build.yml#L18-L25

```yml
env:
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
```

**Pull request merged**
