### PR TITLE
Added sublime settings and workspace extensions.

### PR DESCRIPTION
**Pull request by dnedrow**
This adds two additional extensions for the Sublime text editor.

### CODE REVIEW

**Comment by rpdelaney** [comment]
What about a glob like `.sublime-*` or such? Would that work?

**Comment by rpdelaney** [comment]
@dnedrow ping

**Comment by dnedrow** [comment]
> What about a glob like `.sublime-*` or such? Would that work?

I would think so. I just added them individually to follow the existing pattern.

**Comment by dnedrow** [comment]
> What about a glob like `.sublime-*` or such? Would that work?

@rpdelaney ,

I just tried this and it did not work. I was not able to get a trailing wildcard to work. I tried varying my glob–related shell (ZSH) settings, but nothing worked.

I find it odd because there are working `leading` asterisks that DO work, eg. `*Dockerfile`.

So, at least for the moment, it does NOT appear that `.sublime-*` can be used to cover the sublime variants.

**Comment by rpdelaney** [comment]
Okay, thank you, I could have sworn that was a thing. It will not be hard to redo this if it's ever figured out.

**Comment by dnedrow** [comment]
> Okay, thank you, I could have sworn that was a thing. It will not be hard to redo this if it's ever figured out.

Just as a followup, looking at the source code for both bash and zsh, only the leading asterisk is evaluated. There is no provision for a trailing wildcard. Kind of a bummer, but understandable given that this feature seems to have been motivated by the desire to color files by extension.

**Comment by rpdelaney** [comment]
Great, thanks a bunch for running that down.

**Pull request merged**
